### ISSUE TITLE
Quotations missing from text and examples.

### ISSUE THREAD

**Issue by FreddieMatherSmartDCSIT** [xtuml/otel2puml#203]
Page:  [otel2puml/docs/user/json_data_converter_HOWTO.md at main · xtuml/otel2puml (github.com)](https://github.com/xtuml/otel2puml/blob/main/docs/user/json_data_converter_HOWTO.md)

Throughout the page where arrays are being examples for examples detailed quotations are missing.

This is a fixed version of Example 4,  but expected there are other instances on the page.

 
```yaml
ingest_data:
    data_source: json
    data_holder: sql
data_holders:
    sql:
        db_uri: 'sqlite:///:memory:'
        batch_size: 5
        time_buffer: 0
data_sources:
    json:
        dirpath: /home/abassett/otel2puml/json
        filepath: null
        json_per_line: false
        field_mapping:
            job_name:
                key_paths: ["resource_spans.[].resource.attributes.[].key"]
                key_value: [service.name]
                value_paths: [value.Value.StringValue]
                value_type: string
            job_id:
                key_paths: ["resource_spans.[].scope_spans.[].spans.[].trace_id"]
                value_type: string
            event_type:
                key_paths: [
                    "resource_spans.[].scope_spans.[].spans.[].name",
                    [
                        "resource_spans.[].scope_spans.[].spans.[].attributes.[].key" # this is the fallback path
                    ]
                ]
                key_value: [null, [http.response]]
                value_paths: [null, [value.Value.IntValue]]
                value_type: string
            event_id:
                key_paths: ["resource_spans.[].scope_spans.[].spans.[].span_id"]
                value_type: string
            start_timestamp:
                key_paths: [
                    "resource_spans.[].scope_spans.[].spans.[].start_time_unix_nano"
                ]
                value_type: string
            end_timestamp:
                key_paths: [
                    "resource_spans.[].scope_spans.[].spans.[].end_time_unix_nano"
                ]
                value_type: string
            application_name:
                key_paths: ["resource_spans.[].scope_spans.[].scope.name"]
                value_type: string
            parent_event_id:
                key_paths: ["resource_spans.[].scope_spans.[].spans.[].parent_span_id"]
                value_type: string
```

Outcomes:

- Update README to show examples with quotations for cases with arrays.
- Explain in README that quotations are needed for paths that contain an array
- Reviewed and approved
